config/routes.rb
Rails.application.routes.draw do

  get 'unapproved_reports/index'
  get 'unapproved_reports/show'
  get 'welcome/login'
  post 'welcome/check'
  get 'welcome/destroy'
  post '/ee_report_searchs', to: 'ee_report_searchs#search'
  post '/et_report_searchs', to: 'et_report_searchs#search'
  get 'home/retrieval_top'
  post '/users_search', to: 'users#search' 
  get 'users/bulk_new'
  post 'users/bulk_create', to: 'users#bulk_create'
  get 'home/report_top'
  get 'home/top'
  delete :users, to: 'users#destroy_all'
  resources :ee_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :et_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :users do
    member do
      get :copy
    end
  end
  resources :et_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  resources :ee_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :user_id, uniqueness: {message: "は重複したＩＤを登録できません"}
    validates :user_id, length: { maximum: 9, minimum: 5, message: "は必ず5～9桁で登録してください" }

    validate :error_check
    def error_check
      if user_id.blank?
        errors[:base] << 'ユーザーＩＤは必ず入力してください'
     end        
      if name.blank?
        errors[:base] << '氏名は必ず入力してください'
      end
      if authority.blank?
        errors[:base] << '権限は必ず入力してください。'
      end
    end
    has_secure_password     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :login_check
  before_action :before_controller_check, only: [:new, :edit, :copy]
  before_action :authority_check


  # GET /users
  # GET /users.json
  def index
    @users = User.where(flg: 0).order(:user_id)
    @name = ""
    @annual = ""
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.annual = @user.user_id.slice(1..4)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'ユーザーの作成が完了しました。' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.annual = @user.user_id.slice(1..4)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザーの更新が完了しました。' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json

  def search
    @users = User.all.order(:user_id)
    if params[:search][:annual].present?
      @users = @users.where("annual like '%" + params[:search][:annual] + "%' ").order(:user_id)      
    end
    if params[:search][:name].present?
      @users = @users.where("name like '%" + params[:search][:name] + "%' ").order(:user_id)
  end
    @name = params[:search][:name]
    @annual = params[:search][:annual]
    render :index
  end

  def copy
    old_user = User.find(params[:id])
    @user = User.new(old_user.attributes)
    render :new
    end

  def destroy
    @user.flg = 1
    if @user.update
      format.html { redirect_to @user, notice: 'ユーザーの削除が完了しました。' }
    else
      format.html { render :index }
    end
  end

  def destroy_all
    #チェックしたユーザーのIDを入れるための「checked_data」という空の配列と、削除したユーザーをカウントするための変数「user_count」（初期値は0）を作成
     checked_data = []
     user_count = 0   
    #チェックボックスでチェックしたユーザーのIDが入っているparams[:deletes]が存在していれば、値（key）を取り出して「checked_data」に代入
    checked_data = params[:deletes].keys if params[:deletes].present?

    #「checked_data」の数字とUserモデルのidが一致するデータを取得
    user = User.where(id: checked_data)

    #もしユーザが更新出来たら
    if user.update_all(flg: 1)
      #user_countにchecked_dataの値の数を代入
       user_count = checked_data.size
    end

    #userのindexにredirect_toで画面遷移する。遷移後、「○件のユーザーを削除しました。」とメッセージが表示するようにする。
    redirect_to users_path, notice: "#{user_count}件のユーザーを削除しました。" 
  end
  # CSVインポートページの表示
  def bulk_new
  end

  def bulk_create
    user_count = import_users
    redirect_to users_path, notice: "#{user_count}件登録しました"
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :name, :password, :password_confirmation, :flg, :annual, :authority)
    end

    def import_users
      # 登録処理前のレコード数
      current_user_count = ::User.count
      users = []
      u_id = User.maximum(:id) + 1
      # windowsで作られたファイルに対応するので、encoding: "SJIS"を付けている
      CSV.foreach(params[:users_file].tempfile.path, headers: true, encoding: "SJIS") do |row|
        users << User.new( user_id: "#{row["user_id"]}", name: "#{row["name"]}", password: "#{row["password"]}", flg: row["flg"] , annual: row["annual"], authority: row["authority"])
      end
      # importメソッドでバルクインサートできる
      ::User.import(users)
      # 何レコード登録できたかを返す
      ::User.count - current_user_count
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "") %>つのエラーが発生しています。修正してください。</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ユーザーid %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :氏名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :パスワード %>
    <%= form.password_field :password %>
    <%= form.label :パスワード再入力 %>
    <%= form.password_field :password_confirmation %>
  </div>


  <div class="field">
    <%= form.label :年度 %>
    <%= form.text_field :annual %>
  </div>

    <%= form.hidden_field :flg, :value => "0" %>

  <div class="field">
    <%= form.label :権限 %>
  </div>
  <label><%= form.radio_button :authority, "1" %> 教員</label>
  <label><%= form.radio_button :authority, "2" %> 生徒</label>
  <label><%= form.radio_button :authority, "3" %> 閲覧のみ</label>
  

  <div class="actions">
    <%= form.submit :登録%>
  </div>
<% end %>

app/views/users/bulk_new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

<h1>ユーザー一括登録</h1>

<div>
  <%= form_with url: users_bulk_create_path, multipart: true do |f| %>
    <div class="search_item">
      <%= f.file_field 'users_file' %>
    </div>
    <br>
    <div>
      <button type="submit" class="btn btn-primary">CSVインポート</button>
    </div>
  <% end %>
</div>

<br>
<%= link_to '戻る', users_path %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= render 'form', user: @user %>

<%= link_to '詳細', @user %> |
<%= link_to '戻る', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ログインユーザー一覧</h1>

<%= form_tag('/users_search') do %>
  <p>
  名前（部分一致）
  <br>
  <%= text_field_tag 'search[name]',@name %>
  </p>
  <p>
  年度
  <br>
  <%= text_field_tag 'search[annual]',@annual %>
  </p>
   <input type="submit" style="width:15%;padding:10px;font-size:20px;" value="検&emsp;&emsp;索" >
 <% end %>

<br>
<div>
  <%= link_to '新規登録', new_user_path %>&emsp;&emsp;&emsp;<%= link_to '一括登録', users_bulk_new_path %>
</div>
<br>

<%= form_tag({ controller: :users, action: :destroy_all },method: 'delete') do %>
<table border="1" cellspacing="0" bordercolor="#000000" width="50%" >
  <thead>
    <tr>
      <th width="25%">ユーザー名</th>
      <th width="25%">ユーザーID</th>
      <th colspan="3"></th>
      <th width="10%">削除</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.user_id %></td>
        <td align="center"><%= link_to '詳細', user_path(user) %></td>
        <td align="center"><%= link_to '編集', edit_user_path(user) %></td>
        <td align="center"><%= link_to '複写', copy_user_path(user) %></td>
        <td align="center"><%= check_box_tag "deletes[#{ user.id }]", user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= submit_tag '一括削除', data: { confirm: "選択したユーザーを削除してもよろしいですか？"} %>
<% end %>

<p><%= link_to 'トップへ戻る', home_top_path %></p>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ユーザーid:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>氏名:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>パスワード:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>年度:</strong>
  <%= @user.annual %>
</p>


<%= link_to '一覧へ戻る', users_path %>