config/routes.rb
Rails.application.routes.draw do

  get 'unapproved_reports/index'
  get 'unapproved_reports/show'
  get 'welcome/login'
  post 'welcome/check'
  get 'welcome/destroy'
  post '/ee_report_searchs', to: 'ee_report_searchs#search'
  post '/et_report_searchs', to: 'et_report_searchs#search'
  get 'home/retrieval_top'
  post '/users_search', to: 'users#search' 
  get 'users/bulk_new'
  post 'users/bulk_create', to: 'users#bulk_create'
  get 'home/report_top'
  get 'home/top'
  delete :users, to: 'users#destroy_all'
  resources :ee_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :et_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :users do
    member do
      get :copy
    end
  end
  resources :et_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  resources :ee_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :login_check
  # before_action :before_controller_check

  def retrieval_top
      @user_authority = User.find_by(user_id: session[:login_id]).authority
  end
  
  def top
    @ee_reports = EeReport.where(student_id: session[:login_id],approval_flg: 0)
    @et_reports = EtReport.where(student_id: session[:login_id],approval_flg: 0)
    @user_authority = User.find_by(user_id: session[:login_id]).authority
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/report_top.html.erb
<h1 style="text-align: center;">報告書登録</h1>
<p style="line-height: 30px; text-align: center;"><%= link_to '就職試験受験報告書登録', new_et_report_path %></p>
<p style="line-height: 30px; text-align: center;"><%= link_to '入学試験受験報告書登録', new_ee_report_path %></p>
<p style="line-height: 30px; text-align: center;"><%= link_to 'トップへ戻る', home_top_path %></p>

app/views/home/retrieval_top.html.erb
<% if @user_authority == 1 or @user_authority == 2 %>
  <h1 style="text-align: center;">報告書検索</h1>
<% else %>
<h1 style="text-align: center;">トップページ</h1>
<% end %>

<p style="line-height: 30px; text-align: center;"><%= link_to '就職試験受験報告書検索', et_report_searchs_path %></p>
<p style="line-height: 30px; text-align: center;"><%= link_to '入学試験受験報告書検索', ee_report_searchs_path %></p>
<% if @user_authority == 1 or @user_authority == 2 %>
  <p style="line-height: 30px; text-align: center;"><%= link_to 'トップへ戻る', home_top_path %></p>
<% end %>

app/views/home/top.html.erb
<% if flash[:error] %>
    <p style="color: red;">
      <%= flash[:error] %>
    </p>
<% end %>
<h1 style="text-align: center;">トップページ</h1>
<% if @user_authority == 2 %>
<p style="line-height: 30px; text-align: center;"><%= link_to '報告書の登録', home_report_top_path %></p>
<% end %>
<p style="line-height: 30px; text-align: center;"><%= link_to '報告書の検索', home_retrieval_top_path %></p>
<% if @user_authority == 1 %>
  <p style="line-height: 30px; text-align: center;"><%= link_to 'ログインユーザ－一覧', users_path %></p>
<% end %>
<% if @user_authority == 1 %>
  <p style="line-height: 30px; text-align: center;"><%= link_to '報告書未承認一覧', unapproved_reports_index_path %></p>
<% end %>


<% if  @user_authority == 2 %>
<h2>未承認一覧</h2>
<div style="height:400px; overflow-y:auto;">
<table>
  <thead>
    <tr>
    <th width="35%">受験者ID</th>
    <th width="35%">学校名・企業名</th>
    <th width="30%"></th>
    </tr>
  </thead>
</table>
 
<table>
  <tbody>
    <% @ee_reports.each do |ee_report| %>
      <tr>
        <td width="35%"><%= ee_report.student_id %></td>
        <td width="35%"><%= ee_report.school_name %></td>
        <td width="15%"><%= link_to '閲覧', ee_report %></td>
        <td width="15%"><%= link_to '複写', copy_ee_report_path(ee_report) %></td>
      </tr>
    <% end %>

    <% @et_reports.each do |et_report| %>
      <tr>
        <td width="35%"><%= et_report.student_id %></td>
        <td width="35%"><%= et_report.office_name %></td>
        <td width="15%"><%= link_to '閲覧', et_report %></td>
        <td width="15%"><%= link_to '複写', copy_et_report_path(et_report) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% end %>