config/routes.rb
Rails.application.routes.draw do

  get 'unapproved_reports/index'
  get 'unapproved_reports/show'
  get 'welcome/login'
  post 'welcome/check'
  get 'welcome/destroy'
  post '/ee_report_searchs', to: 'ee_report_searchs#search'
  post '/et_report_searchs', to: 'et_report_searchs#search'
  get 'home/retrieval_top'
  post '/users_search', to: 'users#search' 
  get 'users/bulk_new'
  post 'users/bulk_create', to: 'users#bulk_create'
  get 'home/report_top'
  get 'home/top'
  delete :users, to: 'users#destroy_all'
  resources :ee_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :et_report_searchs do
    # collection do
    #   post :search
    # end
  end
  resources :users do
    member do
      get :copy
    end
  end
  resources :et_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  resources :ee_reports do
    member do
      get :copy
    end
    collection do
      post :output
      post :approval
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/et_report.rb
class EtReport < ApplicationRecord

  validate :error_check
    def error_check
      if reporting_date > Date.today
          errors[:base] << '報告年月日が今日以降の値です'
      end

      if reporting_date < test_day
          errors[:base] << '報告年月日が試験日より前です'
      end

      if student_class.blank?
          errors[:base] <<  '組は必ず入力してください。'
      elsif student_class.to_i <= 0 or student_class.to_i > 4
            errors[:base] << '組は1以上4以下で入力してください。'
      end

      if student_number.blank?
          errors[:base] << '番号は必ず入力してください。'
      elsif student_number.to_i <= 0 or student_number.to_i >40
            errors[:base] << '番号は1以上40以下で入力してください。'
      end

      if student_id.blank?
          errors[:base] << '受験者IDは必ず入力してください。'
      end

      if job_category.blank?
          errors[:base] << '職種は必ず入力してください。'
      end

      if office_name.blank?
          errors[:base] << '事業所名は必ず入力してください。'
      end

      if job_vote_number.present?
        if job_vote_number.to_i <= 0
          errors[:base] << '求人票受付番号が利用できない値です。'
        end
      end

      if test_day > Date.today
          errors[:base] << '試験日が今日以降の値です'
      end

      if introduction_number.blank?
          errors[:base] << '学校斡旋か縁故か選択してください。'
      end

      if postal_code.present?
        if postal_code.to_i <= 0
          rrors[:base] << '郵便番号が利用できない値です。'
        end
      end

      if street_address.blank?
          errors[:base] << '所在地は必ず入力してください。'
      end

      if examination_hall.blank?
          errors[:base] << '試験会場は必ず入力してください。'
      end

      if selection_method.blank?
          errors[:base] << '選考方法を選択してください。'
      end


    end
end

app/controllers/et_reports_controller.rb
class EtReportsController < ApplicationController
  before_action :set_et_report, only: [:show, :edit, :update, :destroy]
  before_action :login_check
  before_action :before_controller_check, only: [:show]
  # GET /et_reports
  # GET /et_reports.json
  def index
    @et_reports = EtReport.all
  end

  # GET /et_reports/1
  # GET /et_reports/1.json
  def show
  end

  # GET /et_reports/new
  def new
    @et_report = EtReport.new(student_id:session[:login_id])
  end

  # GET /et_reports/1/edit
  def edit
  end

  # POST /et_reports
  # POST /et_reports.json
  def create
    @et_report = EtReport.new(et_report_params)
    if params[:et_report][:i_image].present?
        @et_report.i_image = params[:et_report][:i_image].original_filename
        
        File.open("public/images/#{@et_report.i_image}",'w+b') { |f|
        f.write(params[:et_report][:i_image].read)}
    end
            
    respond_to do |format|
      if @et_report.save
        format.html { redirect_to @et_report, notice: 'Et report was successfully created.' }
        format.json { render :show, status: :created, location: @et_report }
      else
        format.html { render :new }
        format.json { render json: @et_report.errors, status: :unprocessable_entity }
      end
    end
  end




  # PATCH/PUT /et_reports/1
  # PATCH/PUT /et_reports/1.json
  def update
    if params[:et_report][:i_image].present?
        @et_report.i_image = params[:et_report][:i_image].original_filename
        
        File.open("public/images/#{@et_report.i_image}",'w+b') { |f|
        f.write(params[:et_report][:i_image].read)}
    end
    
    if params[:et_report][:i_image].present?
      params[:et_report][:i_image] = params[:et_report][:i_image].original_filename
    else
      params[:et_report][:i_image]  = ""
    end

    respond_to do |format|
      if @et_report.update(et_report_params)
        format.html { redirect_to @et_report, notice: '更新が完了しました。' }
        format.json { render :show, status: :ok, location: @et_report }
      else
        format.html { render :edit }
        format.json { render json: @et_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /et_reports/1
  # DELETE /et_reports/1.json
  def destroy
    @et_report.destroy
    respond_to do |format|
      format.html { redirect_to et_reports_url, notice: '削除が完了しました。' }
      format.json { head :no_content }
    end
  end

  def copy
    old_et_report = EtReport.find(params[:id])
    @et_report = Etreport.new(old_et_report.attributes)
    render :new
    end

  def output
    if params[:et_report][:i_image].present?
      @et_report.i_image = params[:et_report][:i_image].original_filename
      
      File.open("public/images/#{@et_report.i_image}",'w+b') { |f|
      f.write(params[:et_report][:i_image].read)}
  end
      if params[:et_report][:i_image].present?
        params[:et_report][:i_image] = params[:et_report][:i_image].original_filename
        else
        params[:et_report][:i_image]  = ""
      end
    et_report = EtReport.find(params[:output_id])
    # ThinreportsでPDFを作成
    # Editorで作ったtlfファイルを読み込む
    # 1ページ目
    report = Thinreports::Report.new(layout: "#{Rails.root}/app/views/et_reports/就職試験報告書_表.tlf")
    report.start_new_page
    report.page.item(:reporting_date).value(et_report.reporting_date.strftime("%Y年%m月%d日") )
    report.page.item(:student_class).value(et_report.student_class)
    report.page.item(:student_number).value(et_report.student_number)
    report.page.item(:student_id).value(et_report.student_id)
    report.page.item(:office_name).value(et_report.office_name)
    report.page.item(:job_category).value(et_report.job_category)
    report.page.item(:job_vote_number).value(et_report.job_vote_number)
    case et_report.introduction_number 
    when 1 
      introduction = "学校斡旋"
    when 2 
      introduction = "縁故"
    end
    report.page.item(:introduction_number).value(introduction)
    report.page.item(:street_address).value(et_report.street_address)
    report.page.item(:test_day).value(et_report.test_day.strftime("%Y年%m月%d日") )
    report.page.item(:examination_hall).value(et_report.examination_hall)
    report.page.item(:examinees_count_man).value(et_report.examinees_count_man)
    report.page.item(:examinees_count_woman).value(et_report.examinees_count_woman)
    report.page.item(:examinees_count_total).value("#{et_report.examinees_count_man + et_report.examinees_count_woman}")
    case et_report.selection_method
    when 1 
      selection = "一次"
    when 2
      selection = "二次"
    end
    report.page.item(:selection_method).value(selection)
    case et_report.s_method_writing
    when true
      writing = "有"
    when false
      writing = "無"
    end  
    report.page.item(:s_method_writing).value(writing)
    case et_report.s_method_appropriate
    when true
      appropriate = "有"
    when false 
      appropriate = "無"
    end
    report.page.item(:s_method_appropriate).value(appropriate)
    case et_report.s_method_interview
    when true
      interview = "有"
    when false 
      interview = "無"
    end
    report.page.item(:s_method_interview).value(interview)
    case et_report.s_method_composition
    when true
      composition = "有"
    when false
      composition = "無"
    end
    report.page.item(:s_method_composition).value(composition)
    case et_report.s_method_physical
    when true
      physical = "有"
    when false
      physical = "無"
    end
    report.page.item(:s_method_physical).value(physical)
    case et_report.s_method_other
    when true
      other = "有"
    when false
      other = "無"
    end
    report.page.item(:s_method_other).value(other)
    report.page.item(:t_subject_japanese).value(et_report.t_subject_japanese)
    report.page.item(:t_subject_math).value(et_report.t_subject_math)
    report.page.item(:t_subject_society).value(et_report.t_subject_society)
    report.page.item(:t_subject_science).value(et_report.t_subject_science)
    report.page.item(:t_subject_english).value(et_report.t_subject_english)
    report.page.item(:t_subject_other_name).value(et_report.t_subject_other_name)
    report.page.item(:t_subject_other_time).value(et_report.t_subject_other_time)
    report.page.item(:t_subject_general).value(et_report.t_subject_general)
    report.page.item(:t_subject_aptitude).value(et_report.t_subject_aptitude)
    case et_report.i_method_one
    when 1
      method_one = "1人"
    when 2
      method_one = "複数(#{et_report.i_method_count})人"
    when 3
      method_one = "集団討論"
    end
    report.page.item(:i_method_one).value(method_one)
    report.page.item(:judge_count).value(et_report.judge_count)
    report.page.item(:i_time).value(et_report.i_time)
    report.page.item(:i_other).value(et_report.i_other)
    report.page.item(:i_contents).value(et_report.i_contents)
    report.page.item(:i_image).value("#{Rails.root}/public/images/#{et_report.i_image}")
    report.page.item(:composition_title).value(et_report.composition_title)
    report.page.item(:c_sheet_count).value(et_report.c_sheet_count)

   #2ページ目
   report.start_new_page layout: "#{Rails.root}/app/views/et_reports/就職試験報告書_裏.tlf"
   report.page.item(:writing_test_contents).value(et_report.writing_test_contents)
   report.page.item(:other_coment).value(et_report.other_coment)
    
    # PDFファイルのバイナリデータを生成する
    file = report.generate
      # ブラウザでPDFを表示させたい場合
    # パラメタのdisposition: "inline" をつけない場合は、PDFがダウンロードされる
    send_data(
      file,
      filename: "就職試験報告書_#{et_report.office_name}.pdf",
      type: "application/pdf"
      )
  end

  def approval
    et_report = EtReport.find(params[:approval_id])
    et_report.update(approval_flg: 1)
    redirect_to unapproved_reports_index_path, notice: "承認しました。" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_et_report
      @et_report = EtReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def et_report_params
      params.require(:et_report).permit(:reporting_date, :student_class, :student_number, :student_id, :job_category, :office_name, :job_vote_number, :introduction_number, :test_day, :postal_code, :street_address, :examination_hall, :examinees_count_man, :examinees_count_woman, :selection_method, :s_method_writing, :s_method_appropriate, :s_method_interview, :s_method_composition, :s_method_physical, :s_method_other, :t_subject_japanese, :t_subject_math, :t_subject_society, :t_subject_science, :t_subject_english, :t_subject_other_name, :t_subject_other_time, :t_subject_general, :t_subject_aptitude, :i_method_one, :i_method_count, :judge_count, :i_time, :i_other, :i_contents, :i_image, :composition_title, :c_sheet_count, :writing_test_contents, :other_coment,:approval_flg)
    end
end

app/helpers/et_reports_helper.rb
module EtReportsHelper
end

app/views/et_reports/_form.html.erb
<%= form_with(model: et_report, local: true) do |form| %>
  <% if et_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(et_report.errors.count, "") %> つのエラーが発生しています。修正してください。</h2>

      <ul>
      <% et_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    報告年月日<%= form.date_select :reporting_date %>
  </div>

  <br>
    <div style="display:inline-flex">
      <div style="margin-right: 10px;">
        <div class="field">
          3年<%= form.number_field :student_class %>組
      </div>
        </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.number_field :student_number %>番
  </div>
    </div>

  <div style="margin-right: 10px;">
    <div class="field">
      受験者ID<%= form.text_field :student_id,readonly: true, class: 'readonly_text' %>
  </div>
    </div>
  </div>
  </br>

  <br>
    <div style="display:inline-flex">
      <div style="margin-right: 10px;">
        <div class="field">
          職種<%= form.text_field :job_category %>
      </div>
        </div>

  <div class="field">
    事業所名<%= form.text_field :office_name, :size=>"50" %>
  </div>
  </div>
  </br>

  <br>
    <div style="display:inline-flex">
      <div class="field">
        求人票受付番号 <%= form.number_field :job_vote_number %>
      </div>

  <label style="margin-top: 0px;">
    <%= form.radio_button :introduction_number,"1" %>学校斡旋
  </label>
  <label style="margin-top: 0px;">
    <%= form.radio_button :introduction_number,"2" %>縁故
  </label>
    </div>
  </br>

  <div class="field">
    試験日<%= form.date_select :test_day %>
  </div>

  <div style="display:inline-flex">
    <div style="margin-right: 10px;">
      <div class="field">
        <%= form.label :郵便番号 %>〒
          <%= form.number_field :postal_code %>(例6990000)
    </div>
      </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.label :所在地 %>
        <%= form.text_field :street_address, :size=>"50" %>
  </div>
    </div>

  <div class="field">
    <%= form.label :試験会場 %>
      <%= form.text_field :examination_hall, :size=>"50" %>
  </div>
  </div>

  <div class="field">
    <%= form.label :受験者数 %>
  </div>

  <div style="display:inline-flex">
    <div style="margin-right: 10px;">
      <div class="field">
        男<%= form.number_field :examinees_count_man %>人
    </div>
      </div>

  <div class="field">
    女<%= form.number_field :examinees_count_woman %>人
  </div>
  </div>
  
  <%= form.label :選考方法 %>
    <label style="margin-top: 0px;">
      <label><%= form.radio_button :selection_method,"1" %>一次</label>
    </label>
      <label style="margin-top: 0px;">
          <label><%= form.radio_button :selection_method,"2" %>二次</label>
      </label>

  <div style="display:inline-flex">
    <div style="margin-right: 10px;">
      <div class="field">
        <%= form.check_box :s_method_writing %>筆記
    </div>
      </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.check_box :s_method_appropriate %>適正
    </div>
  </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.check_box :s_method_interview %>面接
    </div>
  </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.check_box :s_method_composition %>作文
    </div>
  </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.check_box :s_method_physical %>身体
    </div>
  </div>

  <div style="margin-right: 10px;">
    <div class="field">
      <%= form.check_box :s_method_other %>その他の内容
    </div>
  </div>
  </div>

  <%= form.label :試験科目 %>
    <div style="display:inline-flex">
      <div style="margin-right: 10px;">
        <div class="field">
          <%= form.label :試験時間（国語） %>
            <%= form.number_field :t_subject_japanese %>分
      </div>
        </div>

  <div class="field">
    <div style="margin-right: 10px;">
      <%= form.label :試験時間（数学） %>
        <%= form.number_field :t_subject_math %>分
    </div>
  </div>

  <div class="field">
    <div style="margin-right: 10px;">
      <%= form.label :試験時間（社会） %>
        <%= form.number_field :t_subject_society %>分
    </div>
  </div>

  <div class="field">
    <div style="margin-right: 10px;">
      <%= form.label :試験時間（理科） %>
        <%= form.number_field :t_subject_science %>分
    </div>
  </div>

  <div class="field">
    <div style="margin-right: 10px;">
      <%= form.label :試験時間（英語） %>
        <%= form.number_field :t_subject_english %>分
    </div>
  </div>

  <div class="field">
    <%= form.label :その他の内容 %>
        <%= form.text_field :t_subject_other_name %>
  </div>

  <div class="field">
    <%= form.label :試験時間（その他の内容） %>
      <%= form.number_field :t_subject_other_time %>分
  </div>
  </div>

  <div style="display:inline-flex">
    <div style="margin-right: 10px;">
      <div class="field">
        <%= form.label :試験時間（一般常識） %>
          <%= form.number_field :t_subject_general %>分
      </div>
    </div>

  <div class="field">
    <%= form.label :試験時間（適正） %>
      <%= form.number_field :t_subject_aptitude %>分
  </div>
  </div>

  <br>
    <div style="display:inline-flex">
      <div class="field">
        <%= form.label :面接方法 %>
          <%= form.radio_button :i_method_one,"1" %>1人
            <%= form.radio_button :i_method_one,"2" %>複数
              <%= form.number_field :i_method_count %>人
                <%= form.radio_button :i_method_one,"3" %>集団討論
      </div>

  <div class="field">
    <div style="margin-left: 10px;">
      <%= form.label :面接委員数 %>
        <%= form.number_field :judge_count %>人
    </div>
  </div>

  <div class="field">
    <div style="margin-left: 10px;">
      <%= form.label :面接時間 %>
        <%= form.number_field :i_time %>分
    </div>
  </div>
  
  <div class="field">
    <div style="margin-left: 10px;">
      <%= form.label :その他（面接）%>
        <%= form.text_field :i_other %>
    </div>
  </div>
    </div>
  </br>

  <div class="field">
    <%= form.label :面接内容 %>
      <%= form.text_area :i_contents, :size=>"60x10" %>
  </div>

  <div style="margin-left: 300px;">
    <div class="field">
      <%= form.label :画像 %>
        <%= form.file_field :i_image %>
    </div>
  </div>

  <div class="field">
    <%= form.label :作文（題目） %>
      <%= form.text_field :composition_title, :size=>"50" %>
  </div>

  <div class="field">
    <%= form.label :用紙数 %>
      <%= form.number_field :c_sheet_count %>枚
  </div>

  <div class="field">
    <%= form.label :筆記試験内容 %>
      <%= form.text_area :writing_test_contents, :size=>"60x10" %>
  </div>

  <div class="field">
    <%= form.label :参考になること記入 %>
      <%= form.text_area :other_coment, :size=>"60x10" %>
  </div>

  <div>
    <%= form.hidden_field :approval_flg, :value => "0"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/et_reports/edit.html.erb
<h1 style="text-align: center;">報告書の編集</h1>

<%= render 'form', et_report: @et_report %>

<%= link_to '閲覧', @et_report %> |
<%= link_to '戻る', home_top_path %>

app/views/et_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>就職試験受験報告書一覧</h1>

<table border="1"> 
  <thead>
    <tr>
      <th>報告年月日</th>
      <th>組</th>
      <th>番号</th>
      <th>受験者ID</th>
      <th>職種</th>
      <th>事業所名</th>
      <th>求人票受付番号</th>
      <th>紹介番号</th>
      <th>試験日</th>
      <th>郵便番号</th>
      <th>所在地</th>
      <th>試験会場</th>
      <th>選考方法</th>
      <th>面接画像</th>
      <th>承認フラグ</th>

      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @et_reports.each do |et_report| %>
      <tr>
    
        <td><%= et_report.reporting_date.strftime("%Y年%m月%d日") %></td>
        <td><%= et_report.student_class %></td>
        <td><%= et_report.student_number %></td>
        <td><%= et_report.student_id %></td>
        <td><%= et_report.job_category %></td>
        <td><%= et_report.office_name %></td>
        <td><%= et_report.job_vote_number %></td>
        <td><%= et_report.introduction_number %></td>
        <td><%= et_report.test_day.strftime("%Y年%m月%d日") %></td>
        <td><%= et_report.postal_code %></td>
        <td><%= et_report.street_address %></td>
        <td><%= et_report.examination_hall %></td>
        <td><%= et_report.selection_method %></td>
        <td>
          <% if et_report.i_image.present? %>
          <br>
          <%= image_tag "/images/#{et_report.i_image}",width: 200 %>
          <% end %>
        </td>
        <td><%= et_report.approval_flg %></td>
        <td><%= link_to '閲覧', et_report %></td>
        <td><%= link_to '編集', edit_et_report_path(et_report) %></td>
        <td><%= link_to '削除', et_report, method: :delete, data: { confirm: '削除してもよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to '報告書作成', new_et_report_path %></td>

<br>

<td><%= link_to 'トップページへ戻る', home_top_path %></td>

app/views/et_reports/new.html.erb
<h1 style="text-align: center;">報告書の作成</h1>

<%= render 'form', et_report: @et_report %>

<%= link_to '戻る', home_top_path %>

app/views/et_reports/show.html.erb
<p id="notice"><%= notice %></p>

<table width = "90%" border = "1">


  <tr>
    <th colspan="4" rowspan="2">就職試験受験報告書</th>
    <th>進路指導部長</th>
    <th>学年主任</th>
    <th>担任</th>
    <th>報告年月日</th>
  </tr>

  <tr>
    <td></td><td></td><td></td><td><%= @et_report.reporting_date.strftime("%Y年%m月%d日") %></td>
  </tr>

  <tr>
    <th>受験者</th>
    <td colspan="2">3年<%= @et_report.student_class %>組<%= @et_report.student_number %>番</td>
    <th>氏名</th>
    <td colspan="2"><%= @et_report.student_id %></td>
    <th>職種</th>
    <td><%= @et_report.job_category %></td>
  </tr>

  <tr>
    <th>事業所名</th>
      <td colspan="4"><%= @et_report.office_name %></td>
    <th>求人票受付番号</th>
      <td><%= @et_report.job_vote_number %></td>
    <% case @et_report.introduction_number %>
    <% when 1 then %>
      <% introduction_number = "学校斡旋" %>
    <% when 2 then %>
      <% introduction_number = "縁故" %>
      <% end %>
        <td><%=  introduction_number %></td>
  </tr>
  <tr>
    <th>所在地</th>
      <td colspan="5"><%= @et_report.street_address %></td>
  <th>試験日</th>
      <td><%= @et_report.test_day.strftime("%m月%d日") %></td>
  </tr>

  <tr>
    <th>試験場</th>
      <td colspan="4"><%= @et_report.examination_hall %></td>
    <th>受験者数</th>
      <td colspan="2">男<%= @et_report.examinees_count_man %>人 女<%= @et_report.examinees_count_woman %>人 計<%= "#{@et_report.examinees_count_man + @et_report.examinees_count_woman}" %>人</td> 
  </tr>
</table>

  <table width = "90%" border = "1">
    <tr>
      <th rowspan="2">選考方法</th>
         <% case @et_report.selection_method %>
         <% when 1 then %>
            <% selection_method = "一次" %>
         <% when 2 then %>
            <% selection_method = "二次" %>
         <% end %>
  <td rowspan="2"><center><%= selection_method %></center></td>
    <th>筆記試験</th>
    <th>適正試験</th>
    <th>　面接　</th>
    <th>　作文　</th>
    <th>身体検査</th>
    <th><center>その他　</center></th>
  </tr>

  <tr>
    <% case @et_report.s_method_writing %>
    <% when true then %>
      <% s_method_writing = "有" %>
    <% when false then %>
      <% s_method_writing = "無" %>
    <% end %>
<td><%= s_method_writing %></td>
<% case @et_report.s_method_appropriate %>
    <% when true then %>
      <% s_method_appropriate = "有" %>
    <% when false then %>
      <% s_method_appropriate = "無" %>
    <% end %>
<td><%= s_method_appropriate %></td>
<% case @et_report.s_method_interview %>
     <% when true then %>
      <% s_method_interview = "有" %>
    <% when false then %>
      <% s_method_interview = "無" %>
    <% end %>
<td><%= s_method_interview %></td>
<% case @et_report.s_method_composition %>
     <% when true then %>
        <% s_method_composition = "有" %>
     <% when false then %>
        <% s_method_composition = "無" %>
     <% end %>
      <td><%= s_method_composition %></td>
<% case @et_report.s_method_physical %>
     <% when true then %>
       <% s_method_physical = "有" %>
     <% when false then %>
       <% s_method_physical = "無" %>
     <% end %>
        <td><%= s_method_physical %></td>
<% case @et_report.s_method_other %>
     <% when true then %>
        <% s_method_other = "有" %>
     <% when false then %>
        <% s_method_other = "無" %>
     <% end %>
        <td><%= s_method_other %></td>
 </tr>
</table>

<table width = "90%" border = "1">
  <tr>
    <th rowspan="2">試験科目</th>
    <th>国語</th>
    <th>数学</th>
    <th>社会</th>
    <th>理科</th>
    <th>英語</th>
  <td><center><%= @et_report.t_subject_other_name %></center></td>
    <th>一般常識</th>
    <th>適正問題</th>
  </tr>
 
  <tr>
    <td><%= @et_report.t_subject_japanese %>分</td>
    <td><%= @et_report.t_subject_math %>分</td>
    <td><%= @et_report.t_subject_society %>分</td>
    <td><%= @et_report.t_subject_science %>分</td>
    <td><%= @et_report.t_subject_english %>分</td>
    <td><%= @et_report.t_subject_other_time %>分</td>
    <td><%= @et_report.t_subject_general %>分</td>
    <td><%= @et_report.t_subject_aptitude %>分</td>
  </tr>
</table>

<table width = "90%" border = "1">
  <tr>
    <th rowspan="7">面接内容・質問内容</th>
  </tr>
   <th colspan="5">面接方法(受験者数)</th>
   <th>面接委員</th>
   <th>面接時間</th>
   <th>その他</th>
  <tr>
  <% case @et_report.i_method_one %>
  <% when 1 then %>
    <% i_method_one = "1人" %>
  <% when 2 then %>
    <% i_method_one = "複数(#{@et_report.i_method_count})人" %>
  <% when 3 then %>
    <% i_method_one = "集団討論" %>
  <% end %>
  <td colspan="5"><%= i_method_one %></td>
    <td><%= @et_report.judge_count %>人</td>
    <td><%= @et_report.i_time %>分</td>
    <td><%= @et_report.i_other %></td>
 </tr>

  <td colspan="8"><%= @et_report.i_contents %> <br> <% if  @et_report.i_image.present? %>  <%= image_tag "/images/#{@et_report.i_image}",width: 400 %><% end %></td>
</table>

<table width = "90%" border = "1">
  <tr>
    <th>作文</th>
    <th>題目</th>
 <td colspan="6"><%= @et_report.composition_title %></td>
    <td>原稿用紙(400字詰)<%= @et_report.c_sheet_count %>枚位</td>
 </tr>
</table>

<table width = "90%" border = "1">
  <th>筆記試験問題(内容)＊できるかぎり詳しく書いてください。</th>
    <tr>
    <td><%= @et_report.writing_test_contents %></td>
    </tr>
  <td>＊受験上参考になることがあれば記入してください。(失敗事例を含め)<br><%= @et_report.other_coment %></td>
</table>



<% if @user_authority == 3 %>
  <%= link_to '編集', edit_ee_report_path(@ee_report) %> 
<% end %>
<div>
  <%= link_to '戻る', home_top_path %> 
</div><br>

<div>
  <%= form_tag('/et_reports/output') do %>
    <%= hidden_field_tag "output_id", @et_report.id %>
    <input type="submit" style="width:10%;padding:10px;font-size:20px;" value="印&emsp;&emsp;刷" >
  <% end %>
</div><br><br>
<% if @path[:controller] == "unapproved_reports" %>
  <%= form_tag('/et_reports/approval') do %>
    <input type="submit" style="width:10%;padding:10px;font-size:20px;" value="承&emsp;&emsp;認" >
    <%= hidden_field_tag "approval_id", @et_report.id %>
  <% end %>
<% end %>